config/routes.rb
Rails.application.routes.draw do
  root to: 'front_page#index'

  
  resources :packages do
  	resources :years do
  		resources :users
  	end
  end

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :year
	# has_many :packages, :through => :years
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_year
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_admin!, only: [:new]

  # GET /users
  # GET /users.json
  def index
    @users = @year.users
    respond_to :html, :json
  end

  # GET /users/new
  def new
    @user = @year.users.build
    respond_to :html, :json
  end

  # GET /users/1/edit
  def edit
    @user = @year.users.find(params[:id])
    respond_to :html, :json
  end

  # POST /users
  # POST /users.json
  def create
    @user = @year.users.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = @year.users.find(params[:id])
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = @year.users.find(params[:id])
    
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:year_id])
    end

    def set_user
      @user = @year.users.find(:id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :telephone, :year_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for [:package, @year, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label 'Nome completo:'
    = f.text_field :name, placeholder: "Seu nome completo aqui",class: "form-control"
  .form-group
    = f.label "Email:"
    = f.text_field :email, placeholder: "exemplo@email.com",class: "form-control"
  .form-group
    = f.label "Celular/Whatsaap: "
    = f.text_field :telephone, placeholder:"(99)99999-9999",class: "form-control"
  .actions = f.submit 'Registrar-se', class: "btn btn-success btn-lg btn-block"

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
.container
  h1 Listing users

  table.table.table-bordered
    thead
      tr
        th Name
        th Email
        th Telephone
        th
        th

    tbody
      - @users.each do |user|
        tr
          td = user.name
          td = user.email
          td = user.telephone
          td = link_to 'Edit', edit_package_year_user_path(@year.package ,@year, user)
          / td = link_to 'Destroy', package_year_user, data: { confirm: 'Tem certeza?' }, method: :delete

  br

   / = link_to 'New User', new_user_pth

app/views/users/new.html.slim
.container 
	h1 Registrar-se em:
	= content_tag :h1, "Pacote: #{@year.package.name}"
	= content_tag :h1, "Ano: #{@year.name}"

	== render 'form'

	/ = link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email
p
  strong Telephone:
  = @user.telephone

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path