config/routes.rb
Rails.application.routes.draw do
  root to: 'front_page#index'

  
  resources :packages do
  	resources :years do
  		resources :users
  	end
  end

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :package
  has_many :users
end

app/controllers/years_controller.rb
  class YearsController < ApplicationController
  before_action :set_package_id
  before_action :set_year, only: [:show, :edit, :update, :destroy]

  # GET /years
  # GET /years.json
  def index
    @years = @package.years
    respond_to :html, :json
  end

  # GET /years/1
  # GET /years/1.json
  def show
    @year = @package.years.find(params[:id])
    respond_to :html, :json
  end

  # GET /years/new
  def new
    @year = @package.years.build
    respond_to :html, :json
  end

  # GET /years/1/edit
  def edit
    @year = @package.years.find(params[:id])
    respond_to :html, :json
  end

  # POST /years
  # POST /years.json
  def create
    @year = @package.years.create(params[:year])

    respond_to do |format|
      if @year.save
        format.html { redirect_to @year, notice: 'Year was successfully created.' }
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1
  # PATCH/PUT /years/1.json
  def update
    @year = @package.years.find(params[:id])

    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to @year, notice: 'Year was successfully updated.' }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1
  # DELETE /years/1.json
  def destroy
    @year = @package.years.find(params[:id])
    @year.destroy
    respond_to do |format|
      format.html { redirect_to years_url, notice: 'Year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_id
      @package = Package.find(params[:package_id])
    end

    def set_year
      @year = @package.years.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def year_params
      params.require(:year).permit(:name, :package_id)
    end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.slim
= form_for @year do |f|
  - if @year.errors.any?
    #error_explanation
      h2 = "#{pluralize(@year.errors.count, "error")} prohibited this year from being saved:"
      ul
        - @year.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :package
    = f.text_field :package
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/years/edit.html.slim
h1 Editing year

== render 'form'

= link_to 'Show', @year
'|
= link_to 'Back', years_path

app/views/years/index.html.slim
h1 Listing years

table
  thead
    tr
      th Name
      th Package
      th
      th
      th

  tbody
    - @years.each do |year|
      tr
        td = year.name
        td = year.package.name
        / td = year.users.name
        td = link_to 'Show', package_year_path(year)
        td = link_to 'Edit', edit_package_year_path(year)
        td = link_to 'Destroy', year, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Year', new_year_path

app/views/years/new.html.slim
h1 New year

== render 'form'

= link_to 'Back', years_path

app/views/years/show.html.slim
p#notice = notice

p
  strong Name:
  = @year.name
p
  strong Package:
  = @year.package.name
p
  strong Users:
  - @year.users.each do |year_users|
  	p = year_users.name

= link_to 'Edit', edit_package_year_path(@year)